# This is your rocks.nvim plugins declaration file.
# Here is a small yet pretty detailed example on how to use it:
#
# [plugins]
# nvim-treesitter = "semver_version"  # e.g. "1.0.0"

[config]
plugins_dif = "plugins/"
auto_setup = false

# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]

# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]
"fidget.nvim" = "1.6.0"
"gitsigns.nvim" = "1.0.2"
"lazydev.nvim" = "1.9.0"
"mini.animate" = "0.16.0"
"mini.cursorword" = "0.16.0"
"mini.diff" = "0.16.0"
"mini.hues" = "0.16.0"
"mini.indentscope" = "0.16.0"
"mini.jump" = "0.15.0"
"mini.pairs" = "0.16.0"
"mini.pick" = "0.16.0"
"mini.sessions" = "0.16.0"
"mini.starter" = "0.16.0"
"mini.trailspace" = "0.16.0"
"mini.visits" = "0.16.0"
"oil.nvim" = "2.15.0"
"rocks-config.nvim" = "3.1.2"
"rocks-git.nvim" = "2.5.6"
"rocks.nvim" = "2.46.1"
"trouble.nvim" = "3.7.1"
github-nvim-theme = "1.1.2"
nvim-web-devicons = "0.100"
rustaceanvim = "6.9.4"
tree-sitter-javascript = "0.0.39"
tree-sitter-jsx = "0.0.30"
tree-sitter-lua = "0.0.36"
tree-sitter-rust = "0.0.51"
tree-sitter-tsx = "0.0.36"
tree-sitter-typescript = "0.0.37"

[plugins."nvim-autopairs"]
git = "https://github.com/windwp/nvim-autopairs"
rev = "0.10.0"

[plugins."blink.cmp"]
git = "https://github.com/Saghen/blink.cmp"
rev = "v1.7.0"

[plugins."plenary.nvim"]
git = "https://github.com/nvim-lua/plenary.nvim"
rev = "v0.1.4"

[plugins.nvim-spectre]
git = "https://github.com/nvim-pack/nvim-spectre"
rev = "72f56f7585903cd7bf92c665351aa585e150af0f"


[plugins."sonokai"]
git = "https://github.com/sainnhe/sonokai"
rev = "v0.3.3"

[plugins."copilot.vim"]
git = "https://github.com/github/copilot.vim"
rev = "v1.56.0"

[plugins.nvim-lspconfig]
git = "https://github.com/neovim/nvim-lspconfig"
rev = "v2.5.0"

[plugins."vim-repeat"]
git = "https://github.com/tpope/vim-repeat"
rev = "v1.2"

[plugins.hop]
git = "smoka7/hop.nvim"
rev = "v2.7.2"
