[config]
plugins_dif = "plugins/"
auto_setup = false

# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]

# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]
"fidget.nvim" = "1.6.0"
"gitsigns.nvim" = "1.0.2"
"lazydev.nvim" = "1.10.0"
"mini.animate" = "0.17.0"
"mini.cursorword" = "0.17.0"
"mini.diff" = "0.17.0"
"mini.indentscope" = "0.17.0"
"mini.jump" = "0.17.0"
"mini.pairs" = "0.17.0"
"mini.pick" = "0.17.0"
"mini.sessions" = "0.17.0"
"mini.starter" = "0.17.0"
"mini.surround" = "0.17.0"
"mini.trailspace" = "0.17.0"
"mini.visits" = "0.17.0"
"oil.nvim" = "2.15.0"
"rocks-config.nvim" = "3.1.2"
"rocks-git.nvim" = "2.5.7"
"rocks.nvim" = "2.46.1"
"tokyonight.nvim" = "4.14.1"
"trouble.nvim" = "3.7.1"
github-nvim-theme = "1.1.2"
nvim-web-devicons = "0.100"
rustaceanvim = "7.0.6"
tree-sitter-lua = "0.0.36"
tree-sitter-rust = "0.0.55"
tree-sitter-python = "0.0.46"
tree-sitter-typescript = "0.0.38"
tree-sitter-tsx = "0.0.37"
tree-sitter-css = "0.0.39"

[plugins."typescript-tools.nvim"]
git = "https://github.com/pmizio/typescript-tools.nvim"
rev = "c2f5910074103705661e9651aa841e0d7eea9932"

[plugins."nvim-autopairs"]
git = "https://github.com/windwp/nvim-autopairs"
rev = "0.10.0"

[plugins."plenary.nvim"]
git = "https://github.com/nvim-lua/plenary.nvim"
rev = "v0.1.4"

[plugins.nvim-spectre]
git = "https://github.com/nvim-pack/nvim-spectre"
rev = "72f56f7585903cd7bf92c665351aa585e150af0f"

[plugins."blink.cmp"]
git = "https://github.com/saghen/blink.cmp"
rev = "v1.8.0"

[plugins."sonokai"]
git = "https://github.com/sainnhe/sonokai"
rev = "v0.3.3"

[plugins."copilot.vim"]
git = "https://github.com/github/copilot.vim"
rev = "v1.57.0"

[plugins.nvim-lspconfig]
git = "https://github.com/neovim/nvim-lspconfig"
rev = "v2.5.0"

[plugins."vim-repeat"]
git = "https://github.com/tpope/vim-repeat"
rev = "v1.2"

[plugins.hop]
git = "smoka7/hop.nvim"
rev = "v2.7.2"

[plugins."friendly-snippets"]
git = "https://github.com/rafamadriz/friendly-snippets"
rev = "572f5660cf05f8cd8834e096d7b4c921ba18e175"
